# Project
site_name: InvenTree Documentation
site_description: InvenTree - Open Source Inventory Management
site_author: InvenTree
google_analytics: ['UA-143467500-1', 'inventree-docs']

# Repository
repo_url: https://github.com/inventree/inventree-docs
repo_name: inventree/inventree-docs

# Theme
theme:
  name: material
  custom_dir: _includes/overrides
  palette:
    scheme: slate
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - tabs
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

# Navigation
nav:
  - Home: index.md
  - Contribute: contribute.md
  - Getting Started:
    - Installation: start/install.md
    - Configuration: start/config.md
    - Deploying: start/deploy.md
    - Updating: start/update.md
    - Migrating: start/migrate.md
    - Color Themes: start/themes.md
  - Parts:
    - Parts: part/part.md
    - Part Views: part/views.md
    - Parameters: part/parameter.md
    - Template Parts: part/template.md
    - Tests: part/test.md
  - Stock:
    - Stock Items: stock/stock.md
    - Adjusting Stock: stock/adjust.md
    - Stocktake: stock/stocktake.md
    - Test Results: stock/test.md
  - Build:
    - Build Parts: build/build.md
    - BOM: build/bom.md
  - Buy:
    - Suppliers: buy/supplier.md
    - Purchase Orders: buy/po.md
  - Report:
    - Labels: report/labels.md
    - Templates: report/report.md
    - Test Reports: report/test.md
    - Packing List: report/pack.md
    - Order: report/order.md
  - Admin:
    - Admin Interface: admin/admin.md
    - Export Data: admin/export.md
    - Import Data: admin/import.md
  - Extend:
    - API: extend/api.md
    - Python Interface: extend/python.md
    - Plugins: extend/plugins.md
    - Third-Party: extend/integrate.md

# Plugins
plugins:
  - search
  - macros:
      include_dir: _includes

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: ⚓

# Global Variables
extra:
  static_folder_source: ./InvenTree/InvenTree/static/
  static_folder_local_default: ./inventree_static/